# Generated by Django 5.1.2 on 2024-10-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
