# Generated by Django 5.1.2 on 2025-02-05 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunters', '0002_blockchainblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDistributionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('pickup_location', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('preferred_pickup_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('collected', 'Collected'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('quality_issue', 'Quality Issue Reported')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_distributions', to='volunters.volunteerregistration')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_date'],
            },
        ),
    ]
