# Generated by Django 5.1.2 on 2025-02-04 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery_type', models.CharField(choices=[('grains', 'Grains & Cereals'), ('pulses', 'Pulses & Lentils'), ('spices', 'Spices & Condiments'), ('oils', 'Cooking Oils'), ('dry_fruits', 'Dry Fruits & Nuts'), ('others', 'Others')], max_length=20)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity in kg')),
                ('expiry_date', models.DateField()),
                ('pickup_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributed_to', models.CharField(max_length=255)),
                ('distribution_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grocerydistribution.groceryrequest')),
            ],
        ),
    ]
