# Generated by Django 5.1.2 on 2025-02-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerydistribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('collected', 'Collected')], default='pending', max_length=20),
        ),
    ]
