# Generated by Django 5.1.2 on 2025-03-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerydistribution', '0002_alter_groceryrequest_status'),
        ('volunters', '0002_blockchainblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryDistributionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', models.DateTimeField()),
                ('distribution_location', models.CharField(max_length=255)),
                ('beneficiary_type', models.CharField(max_length=100)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('beneficiary_contact', models.CharField(max_length=15)),
                ('number_of_households', models.IntegerField()),
                ('persons_per_household', models.IntegerField()),
                ('actual_households_served', models.IntegerField(blank=True, null=True)),
                ('items_distributed', models.JSONField(blank=True, help_text='List of items actually distributed', null=True)),
                ('distribution_proof', models.ImageField(blank=True, null=True, upload_to='grocery_distribution_proofs/')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grocery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_plans', to='grocerydistribution.groceryrequest')),
                ('volunteer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunters.volunteerregistration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroceryDistributionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('feedback_text', models.TextField()),
                ('items_quality_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('packaging_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('missing_items', models.JSONField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='grocerydistribution.grocerydistributionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
