# Generated by Django 5.1.2 on 2025-01-29 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('cooked', 'Cooked Food'), ('raw', 'Raw Food'), ('packaged', 'Packaged Food'), ('beverages', 'Beverages'), ('other', 'Other')], max_length=50)),
                ('quantity', models.CharField(max_length=100)),
                ('expiry_time', models.DateTimeField()),
                ('pickup_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('collected', 'Collected'), ('distributed', 'Distributed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_type', models.CharField(max_length=100)),
                ('beneficiary_count', models.IntegerField()),
                ('distribution_date', models.DateTimeField()),
                ('distribution_location', models.TextField()),
                ('proof_of_distribution', models.ImageField(blank=True, null=True, upload_to='food_distribution_proofs/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('volunteer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunters.volunteerregistration')),
                ('food_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fooddistribution.foodrequest')),
            ],
        ),
    ]
