# Generated by Django 5.1.2 on 2025-02-12 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddistribution', '0001_initial'),
        ('volunters', '0002_blockchainblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('collected', 'Collected'), ('distributed', 'Distributed'), ('cancelled', 'Cancelled'), ('quality_issue', 'Quality Issue Reported')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='FoodQualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('good', 'Good Quality'), ('expired', 'Food Expired'), ('contaminated', 'Food Contaminated'), ('spoiled', 'Food Spoiled'), ('packaging_damaged', 'Packaging Damaged'), ('temperature_issue', 'Temperature Control Issue'), ('other', 'Other Issue')], max_length=20)),
                ('description', models.TextField()),
                ('temperature', models.FloatField(blank=True, help_text='Temperature of the food at the time of pickup (in Celsius).', null=True)),
                ('packaging_integrity', models.BooleanField(default=True, help_text='Is the packaging intact and undamaged?')),
                ('labeling_accuracy', models.BooleanField(default=True, help_text='Are the labels accurate and legible?')),
                ('allergen_check', models.BooleanField(default=True, help_text='Are allergens properly labeled and separated?')),
                ('hygiene_check', models.BooleanField(default=True, help_text='Is the food stored in a hygienic condition?')),
                ('weight_check', models.FloatField(blank=True, help_text='Weight of the food package (in kilograms).', null=True)),
                ('visual_inspection', models.BooleanField(default=True, help_text='Does the food pass visual inspection for spoilage or contamination?')),
                ('smell_test', models.BooleanField(default=True, help_text='Does the food pass the smell test for freshness?')),
                ('expiration_check', models.BooleanField(default=True, help_text='Is the food within its expiration date?')),
                ('storage_condition', models.CharField(blank=True, help_text='Condition of storage (e.g., refrigerated, frozen, room temperature).', max_length=50, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Report Approved'), ('rejected', 'Report Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('food_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_reports', to='fooddistribution.foodrequest')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_quality_reports', to='volunters.volunteerregistration')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
