# Generated by Django 5.1.2 on 2025-02-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddistribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('collected', 'Collected'), ('distributed', 'Distributed'), ('cancelled', 'Cancelled'), ('quality_issue', 'Quality Issue Reported')], default='pending', max_length=20),
        ),
    ]
