# Generated by Django 5.1.2 on 2025-02-20 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddistribution', '0002_alter_foodrequest_status_foodqualityreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_food_distributed', models.FloatField(default=0)),
                ('number_of_beneficiaries', models.IntegerField(default=0)),
                ('food_waste_prevented', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('items', models.JSONField()),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_info', models.CharField(max_length=200)),
                ('reliability_score', models.FloatField(default=5.0)),
                ('donation_history', models.ManyToManyField(related_name='donors', to='fooddistribution.donation')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='fooddistribution.donor'),
        ),
    ]
