# Generated by Django 5.1.2 on 2025-02-06 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddistribution', '0002_update_food_quality_report_field'),
        ('volunters', '0007_delete_foodqualityreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodQualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('good', 'Good Quality'), ('expired', 'Food Expired'), ('contaminated', 'Food Contaminated'), ('spoiled', 'Food Spoiled'), ('packaging_damaged', 'Packaging Damaged'), ('temperature_issue', 'Temperature Control Issue'), ('other', 'Other Issue')], max_length=20)),
                ('description', models.TextField()),
                ('images', models.JSONField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Report Approved'), ('rejected', 'Report Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('food_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_reports', to='fooddistribution.foodrequest')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_quality_reports', to='volunters.volunteerregistration')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
