# Generated by Django 5.1.2 on 2025-02-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddistribution', '0003_foodqualityreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodqualityreport',
            name='images',
        ),
        migrations.AddField(
            model_name='foodqualityreport',
            name='allergen_check',
            field=models.BooleanField(default=True, help_text='Are allergens properly labeled and separated?'),
        ),
        migrations.AddField(
            model_name='foodqualityreport',
            name='expiration_check',
            field=models.BooleanField(default=True, help_text='Is the food within its expiration date?'),
        ),
        migrations.AddField(
            model_name='foodqualityreport',
            name='hygiene_check',
            field=models.BooleanField(default=True, help_text='Is the food stored in a hygienic condition?'),
        ),
        migrations.AddField(
            model_name='foodqualityreport',
            name='labeling_accuracy',
            field=models.BooleanField(default=True, help_text='Are the labels accurate and legible?'),
        ),
        migrations.AddField(
            model_name='foodqualityreport',
            name='packaging_integrity',
            field=models.BooleanField(default=True, help_text='Is the packaging intact and undamaged?'),
        ),
        migrations.AddField(
            model_name='foodqualityreport',
            name='smell_test',
            field=models.BooleanField(default=True, help_text='Does the food pass the smell test for freshness?'),
        ),
        migrations.AddField(
            model_name='foodqualityreport',
            name='storage_condition',
            field=models.CharField(blank=True, help_text='Condition of storage (e.g., refrigerated, frozen, room temperature).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='foodqualityreport',
            name='visual_inspection',
            field=models.BooleanField(default=True, help_text='Does the food pass visual inspection for spoilage or contamination?'),
        ),
        migrations.AddField(
            model_name='foodqualityreport',
            name='weight_check',
            field=models.FloatField(blank=True, help_text='Weight of the food package (in kilograms).', null=True),
        ),
        migrations.AlterField(
            model_name='foodqualityreport',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Temperature of the food at the time of pickup (in Celsius).', null=True),
        ),
    ]
