# Generated by Django 5.1.2 on 2025-02-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddistribution', '0003_distributionmetrics_donation_donor_donation_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='donation_history',
        ),
    ]
