# Generated by Django 5.1.2 on 2025-03-03 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddistribution', '0004_remove_donor_donation_history'),
        ('volunters', '0002_blockchainblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDistributionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', models.DateTimeField()),
                ('distribution_location', models.CharField(max_length=255)),
                ('beneficiary_type', models.CharField(max_length=100)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('beneficiary_contact', models.CharField(max_length=15)),
                ('estimated_beneficiaries', models.IntegerField()),
                ('actual_beneficiaries', models.IntegerField(blank=True, null=True)),
                ('food_condition_on_delivery', models.TextField(blank=True, null=True)),
                ('distribution_proof', models.ImageField(blank=True, null=True, upload_to='distribution_proofs/')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_plans', to='fooddistribution.foodrequest')),
                ('volunteer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunters.volunteerregistration')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('feedback_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='fooddistribution.fooddistributionplan')),
            ],
        ),
    ]
