# Generated by Django 5.1.2 on 2025-03-10 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddistribution', '0005_fooddistributionplan_distributionfeedback'),
        ('volunters', '0002_blockchainblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryDistributionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery_type', models.CharField(choices=[('dry_goods', 'Dry Goods'), ('fresh_produce', 'Fresh Produce'), ('canned_goods', 'Canned Goods'), ('dairy', 'Dairy Products'), ('personal_care', 'Personal Care Items'), ('household', 'Household Items'), ('other', 'Other')], max_length=50)),
                ('items', models.JSONField(help_text='List of grocery items and their quantities')),
                ('total_weight', models.FloatField(blank=True, help_text='Total weight in kilograms', null=True)),
                ('packaging_requirements', models.TextField(blank=True, null=True)),
                ('storage_instructions', models.TextField(blank=True, null=True)),
                ('distribution_date', models.DateTimeField()),
                ('distribution_location', models.CharField(max_length=255)),
                ('beneficiary_type', models.CharField(max_length=100)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('beneficiary_contact', models.CharField(max_length=15)),
                ('number_of_households', models.IntegerField()),
                ('persons_per_household', models.IntegerField()),
                ('actual_households_served', models.IntegerField(blank=True, null=True)),
                ('items_distributed', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunters.volunteerregistration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroceryDistributionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('feedback_text', models.TextField()),
                ('items_quality_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('packaging_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('missing_items', models.JSONField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='fooddistribution.grocerydistributionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
