# Generated by Django 5.1.2 on 2025-03-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddistribution', '0006_grocerydistributionplan_grocerydistributionfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerydistributionplan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='grocerydistributionplan',
            name='volunteer',
        ),
        migrations.DeleteModel(
            name='GroceryDistributionFeedback',
        ),
        migrations.DeleteModel(
            name='GroceryDistributionPlan',
        ),
    ]
