# Generated by Django 5.1.2 on 2025-03-10 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NGOMoneyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(choices=[('operational_costs', 'Operational Costs'), ('emergency_relief', 'Emergency Relief'), ('project_funding', 'Project Funding'), ('infrastructure', 'Infrastructure Development'), ('education_program', 'Education Program'), ('healthcare_program', 'Healthcare Program'), ('food_distribution', 'Food Distribution Program'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='ngo_money_requests/')),
                ('bank_account_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_branch', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('transferred', 'Transferred'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('transfer_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ngo', models.ForeignKey(limit_choices_to={'is_ngo': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NGOMoneyRequestUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('money_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='donations.ngomoneyrequest')),
            ],
        ),
    ]
