# Generated by Django 5.1.2 on 2025-03-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_ngomoneyrequest_ngomoneyrequestupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngomoneyrequest',
            name='supporting_documents',
        ),
        migrations.AddField(
            model_name='ngomoneyrequest',
            name='additional_documents',
            field=models.FileField(blank=True, help_text='Any additional supporting documents', null=True, upload_to='ngo_money_requests/additional/'),
        ),
        migrations.AddField(
            model_name='ngomoneyrequest',
            name='budget_document',
            field=models.FileField(blank=True, help_text='Detailed budget breakdown (Required for new requests)', null=True, upload_to='ngo_money_requests/budgets/'),
        ),
        migrations.AddField(
            model_name='ngomoneyrequest',
            name='necessity_certificate',
            field=models.FileField(blank=True, help_text='Upload certificate proving necessity of funds (Required for new requests)', null=True, upload_to='ngo_money_requests/certificates/'),
        ),
        migrations.AddField(
            model_name='ngomoneyrequest',
            name='project_proposal',
            field=models.FileField(blank=True, help_text='Project proposal if applicable', null=True, upload_to='ngo_money_requests/proposals/'),
        ),
        migrations.AlterField(
            model_name='ngomoneyrequest',
            name='bank_account_name',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='ngomoneyrequest',
            name='bank_account_number',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='ngomoneyrequest',
            name='bank_branch',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='ngomoneyrequest',
            name='bank_name',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='ngomoneyrequest',
            name='ifsc_code',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
