# Generated by Django 5.1.2 on 2025-03-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_remove_ngomoneyrequest_supporting_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngomoneyrequest',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='ngomoneyrequest',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='ngomoneyrequest',
            name='bank_branch',
        ),
        migrations.RemoveField(
            model_name='ngomoneyrequest',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='ngomoneyrequest',
            name='ifsc_code',
        ),
    ]
