# Generated by Django 5.1.2 on 2024-10-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastecollection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='collection_status',
            field=models.CharField(choices=[('On the Way', 'On the Way'), ('Completed', 'Completed'), ('Not Started', 'Not Started')], default='Not Started', max_length=15),
        ),
    ]
