# Generated by Django 5.1.2 on 2025-03-10 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdistribution', '0002_alter_bookrequest_status'),
        ('volunters', '0002_blockchainblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('collected', 'Collected'), ('distribution_planned', 'Distribution Planned'), ('distributed', 'Distributed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BookDistributionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', models.DateTimeField()),
                ('distribution_location', models.CharField(max_length=255)),
                ('beneficiary_type', models.CharField(max_length=100)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('beneficiary_contact', models.CharField(max_length=15)),
                ('number_of_beneficiaries', models.IntegerField()),
                ('education_level', models.CharField(max_length=100)),
                ('subject_preferences', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_plans', to='bookdistribution.bookrequest')),
                ('volunteer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunters.volunteerregistration')),
            ],
        ),
        migrations.CreateModel(
            name='BookDistributionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('feedback_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='bookdistribution.bookdistributionplan')),
            ],
        ),
    ]
