# Generated by Django 5.1.2 on 2025-02-13 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSupplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_type', models.CharField(choices=[('stationery', 'Stationery'), ('bags', 'School Bags'), ('uniforms', 'School Uniforms'), ('shoes', 'School Shoes'), ('books', 'Text Books'), ('other', 'Other Supplies')], max_length=50)),
                ('education_level', models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('higher_secondary', 'Higher Secondary'), ('other', 'Other')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('condition', models.CharField(max_length=100)),
                ('pickup_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('collected', 'Collected'), ('distributed', 'Distributed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSupplyDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributed_to', models.CharField(max_length=255)),
                ('distribution_date', models.DateTimeField(auto_now_add=True)),
                ('beneficiary_count', models.IntegerField()),
                ('distribution_location', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schoolsupplies.schoolsupplyrequest')),
            ],
        ),
    ]
