# Generated by Django 5.1.2 on 2025-03-10 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsupplies', '0001_initial'),
        ('volunters', '0002_blockchainblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSuppliesDistributionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', models.DateTimeField()),
                ('distribution_location', models.CharField(max_length=255)),
                ('beneficiary_type', models.CharField(choices=[('school', 'School'), ('ngo', 'NGO'), ('community_center', 'Community Center'), ('individual_students', 'Individual Students'), ('orphanage', 'Orphanage'), ('other', 'Other')], max_length=50)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('beneficiary_contact', models.CharField(max_length=15)),
                ('number_of_students', models.IntegerField()),
                ('grade_levels', models.JSONField(help_text='List of grade levels receiving supplies')),
                ('actual_students_served', models.IntegerField(blank=True, null=True)),
                ('items_distributed', models.JSONField(blank=True, help_text='List of items actually distributed', null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volunteer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunters.volunteerregistration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSuppliesDistributionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('feedback_text', models.TextField()),
                ('items_condition_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('completeness_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('missing_items', models.JSONField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='schoolsupplies.schoolsuppliesdistributionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSuppliesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_type', models.CharField(choices=[('notebooks', 'Notebooks'), ('textbooks', 'Textbooks'), ('stationery', 'Stationery'), ('uniforms', 'Uniforms'), ('bags', 'School Bags'), ('others', 'Others')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('education_level', models.CharField(choices=[('primary', 'Primary School'), ('middle', 'Middle School'), ('high', 'High School'), ('higher_secondary', 'Higher Secondary'), ('college', 'College'), ('other', 'Other')], max_length=20)),
                ('condition', models.CharField(max_length=100)),
                ('pickup_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('collected', 'Collected'), ('cancelled', 'Cancelled'), ('distribution_planned', 'Distribution Planned'), ('distributed', 'Distributed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='schoolsuppliesdistributionplan',
            name='supplies_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_plans', to='schoolsupplies.schoolsuppliesrequest'),
        ),
        migrations.AlterField(
            model_name='schoolsupplydistribution',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schoolsupplies.schoolsuppliesrequest'),
        ),
        migrations.DeleteModel(
            name='SchoolSupplyRequest',
        ),
    ]
