# Generated by Django 5.1.2 on 2025-02-06 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddistribution', '0002_update_food_quality_report_field'),
        ('volunters', '0005_alter_foodqualityreport_distribution_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodqualityreport',
            name='distribution_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fooddistribution.foodrequest'),
        ),
        migrations.AlterField(
            model_name='foodqualityreport',
            name='issue_type',
            field=models.CharField(choices=[('good', 'Good Quality'), ('expired', 'Food Expired'), ('contaminated', 'Food Contaminated'), ('spoiled', 'Food Spoiled'), ('packaging_damaged', 'Packaging Damaged'), ('temperature_issue', 'Temperature Control Issue'), ('other', 'Other Issue')], max_length=20),
        ),
        migrations.AlterField(
            model_name='foodqualityreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Report Approved - Food Good'), ('rejected', 'Report Approved - Food Rejected')], default='pending', max_length=20),
        ),
    ]
