# Generated by Django 5.1.2 on 2025-03-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGOs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoprofile',
            name='annual_report',
            field=models.FileField(blank=True, null=True, upload_to='ngo_documents/reports/'),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='ngo_documents/registration/'),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='tax_exemption_certificate',
            field=models.FileField(blank=True, null=True, upload_to='ngo_documents/tax/'),
        ),
    ]
